var child = [
  { 'dupe': true, 'type': 4, 'name': '.jpeg', 'dir': 'c0', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/traffic/.jpeg/', 'fetched': true, 'code': 404, 'len': 8515, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': true, 'type': 4, 'name': '07', 'dir': 'c6', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic/07/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '09', 'dir': 'c7', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic/09/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '14', 'dir': 'c8', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic/14/', 'fetched': true, 'code': 200, 'len': 130, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '5', 'dir': 'c9', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic/5/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '6', 'dir': 'c10', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic/6/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '8', 'dir': 'c11', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic/8/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '9', 'dir': 'c12', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic/9/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': false, 'type': 4, 'name': 'api', 'dir': 'c13', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/traffic/api/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 1, 0 ], 'sig': 0xbc11ad1a },
  { 'dupe': true, 'type': 4, 'name': 'python3.9.sfish', 'dir': 'c14', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/traffic/python3.9.sfish/', 'fetched': true, 'code': 404, 'len': 8545, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': true, 'type': 8, 'name': '.html', 'dir': 'c15', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/traffic/.html', 'fetched': true, 'code': 404, 'len': 8512, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6bb3dfe },
  { 'dupe': true, 'type': 8, 'name': '.html.sfish', 'dir': 'c16', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/traffic/.html.sfish', 'fetched': true, 'code': 404, 'len': 8530, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21028e82 }
];
