var child = [
  { 'dupe': true, 'type': 4, 'name': '07', 'dir': 'c0', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/07/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '09', 'dir': 'c1', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/09/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '14', 'dir': 'c2', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/14/', 'fetched': true, 'code': 200, 'len': 130, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '5', 'dir': 'c3', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/5/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '6', 'dir': 'c4', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/6/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '8', 'dir': 'c5', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/8/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '9', 'dir': 'c6', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/9/', 'fetched': true, 'code': 200, 'len': 129, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': 'api', 'dir': 'c7', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/traffic/api/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210f14d3 }
];
