var child = [
  { 'dupe': false, 'type': 4, 'name': '.jpeg', 'dir': 'c0', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/.jpeg/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 1, 0 ], 'sig': 0x210e8ba6 },
  { 'dupe': false, 'type': 4, 'name': 'light', 'dir': 'c3', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/', 'fetched': true, 'code': 200, 'len': 589, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 8, 'issue_cnt': [ 10, 1, 0, 12, 0 ], 'sig': 0x3153dfde },
  { 'dupe': false, 'type': 4, 'name': 'light.sfish', 'dir': 'c4', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/light.sfish/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 3, 0 ], 'sig': 0xd6b7296e },
  { 'dupe': false, 'type': 4, 'name': 'refresh', 'dir': 'c5', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/refresh/', 'fetched': true, 'code': 500, 'len': 17588, 'decl_mime': 'text/plain', 'sniff_mime': 'text/plain', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 3, 0 ], 'sig': 0x739de907 },
  { 'dupe': false, 'type': 4, 'name': 'road', 'dir': 'c6', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/', 'fetched': true, 'code': 200, 'len': 981, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 8, 0, 0, 3, 0 ], 'sig': 0xe0a0bf5d },
  { 'dupe': true, 'type': 4, 'name': 'road.sfish', 'dir': 'c7', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/road.sfish/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6b7296e },
  { 'dupe': false, 'type': 4, 'name': 'token', 'dir': 'c8', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/token/', 'fetched': true, 'code': 406, 'len': 57, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 3, 0 ], 'sig': 0xd6b7296e },
  { 'dupe': false, 'type': 4, 'name': 'traffic', 'dir': 'c9', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/traffic/', 'fetched': true, 'code': 200, 'len': 1568, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 1, 'issue_cnt': [ 5, 0, 0, 2, 0 ], 'sig': 0x8c495f6a },
  { 'dupe': true, 'type': 4, 'name': 'traffic.sfish', 'dir': 'c10', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/traffic.sfish/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6b7296e },
  { 'dupe': false, 'type': 8, 'name': '.html', 'dir': 'c11', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/.html', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 1, 0 ], 'sig': 0x21032923 }
];
