var child = [
  { 'dupe': true, 'type': 4, 'name': '.jpeg', 'dir': 'c0', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/.jpeg/', 'fetched': true, 'code': 404, 'len': 8506, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': true, 'type': 4, 'name': '.sfish', 'dir': 'c4', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/.sfish/', 'fetched': true, 'code': 404, 'len': 8509, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6b178f1 },
  { 'dupe': true, 'type': 4, 'name': '.sfish.sfish', 'dir': 'c5', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/.sfish.sfish/', 'fetched': true, 'code': 404, 'len': 8527, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': false, 'type': 4, 'name': '07', 'dir': 'c6', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/road/07/', 'fetched': true, 'code': 200, 'len': 139, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 3, 0, 0, 1, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '09', 'dir': 'c7', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/road/09/', 'fetched': true, 'code': 200, 'len': 139, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '5', 'dir': 'c8', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/road/5/', 'fetched': true, 'code': 200, 'len': 139, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '8', 'dir': 'c9', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/road/8/', 'fetched': true, 'code': 200, 'len': 139, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '9', 'dir': 'c10', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/road/9/', 'fetched': true, 'code': 200, 'len': 139, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': false, 'type': 4, 'name': 'api', 'dir': 'c11', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/api/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 1, 0 ], 'sig': 0x108577cc },
  { 'dupe': true, 'type': 4, 'name': 'python3.9.sfish', 'dir': 'c12', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/python3.9.sfish/', 'fetched': true, 'code': 404, 'len': 8536, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': true, 'type': 8, 'name': '.html', 'dir': 'c13', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/.html', 'fetched': true, 'code': 404, 'len': 8503, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0xd6bb3dfe },
  { 'dupe': true, 'type': 8, 'name': '.html.sfish', 'dir': 'c14', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/road/.html.sfish', 'fetched': true, 'code': 404, 'len': 8521, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21028e82 }
];
