var child = [
  { 'dupe': false, 'type': 4, 'name': '.jpeg', 'dir': 'c0', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/.jpeg/', 'fetched': true, 'code': 404, 'len': 8509, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 1, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': false, 'type': 4, 'name': '.js', 'dir': 'c2', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/.js/', 'fetched': true, 'code': 404, 'len': 8503, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 3, 0 ], 'sig': 0xd6b178f1 },
  { 'dupe': true, 'type': 4, 'name': '.js.sfish', 'dir': 'c3', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/.js.sfish/', 'fetched': true, 'code': 404, 'len': 8521, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': false, 'type': 4, 'name': '09', 'dir': 'c6', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/light/09/', 'fetched': true, 'code': 200, 'len': 82, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 3, 0, 0, 1, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '10', 'dir': 'c7', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/light/10/', 'fetched': true, 'code': 200, 'len': 83, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '14', 'dir': 'c8', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/light/14/', 'fetched': true, 'code': 200, 'len': 83, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': true, 'type': 4, 'name': '9', 'dir': 'c9', 'linked': 0, 'url': 'http://127.0.0.1:8000/api/light/9/', 'fetched': true, 'code': 200, 'len': 82, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x21091cc8 },
  { 'dupe': false, 'type': 4, 'name': 'api', 'dir': 'c10', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/api/', 'fetched': true, 'code': 404, 'len': 23, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': false, 'child_cnt': 2, 'issue_cnt': [ 2, 1, 0, 2, 0 ], 'sig': 0x1ac72772 },
  { 'dupe': true, 'type': 4, 'name': 'python3.9.sfish', 'dir': 'c11', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/python3.9.sfish/', 'fetched': true, 'code': 404, 'len': 8539, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': false, 'type': 8, 'name': '.html', 'dir': 'c12', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/.html', 'fetched': true, 'code': 404, 'len': 8506, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 3, 0 ], 'sig': 0xd6bb3dfe },
  { 'dupe': false, 'type': 8, 'name': '.html.sfish', 'dir': 'c13', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/light/.html.sfish', 'fetched': true, 'code': 404, 'len': 8524, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 1, 0 ], 'sig': 0x21028e82 }
];
