# Generated by Django 3.2.5 on 2021-07-05 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Light',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The light on the road', max_length=20)),
                ('state', models.CharField(choices=[('A', 'ON'), ('B', 'OFF')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The road name', max_length=20)),
                ('distance', models.FloatField(help_text='The distance of the road')),
                ('direction', models.CharField(choices=[('R', 'Right to left'), ('L', 'Left to right'), ('U', 'Up to down'), ('D', 'down to up')], help_text='The direction of the road', max_length=2)),
                ('status', models.CharField(blank=True, default='A', help_text='Road status availability', max_length=2, null=True)),
                ('light', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='traffic.light')),
            ],
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('count', models.IntegerField(help_text='The total number of cars on the road')),
                ('status', models.CharField(default='mp', max_length=2)),
                ('image', models.ImageField(blank=True, null=True, upload_to='traffic')),
                ('road', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traffic.road')),
            ],
        ),
    ]
