# Generated by Django 3.2.5 on 2021-07-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20210716_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the road', max_length=20)),
                ('state', models.CharField(choices=[('A', 'on'), ('B', 'off')], max_length=2)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
