# Generated by Django 3.2.5 on 2021-07-24 13:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0002_auto_20210716_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the Junction Exchange', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='road',
            name='light',
        ),
        migrations.AddField(
            model_name='road',
            name='state',
            field=models.CharField(blank=True, choices=[('on', 'on'), ('off', 'off')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='traffic_queue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='road',
            name='exchange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='traffic.exchange'),
        ),
    ]
