# Generated by Django 3.2.5 on 2021-07-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traffic', '0003_roads'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roads',
            new_name='Junction',
        ),
    ]
