var child = [
  { 'dupe': false, 'type': 4, 'name': 'api', 'dir': 'c0', 'linked': 1, 'url': 'http://127.0.0.1:8000/api/', 'fetched': true, 'code': 200, 'len': 132, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': true, 'child_cnt': 19, 'issue_cnt': [ 32, 1, 0, 29, 0 ], 'sig': 0xe9e80153 },
  { 'dupe': false, 'type': 4, 'name': 'api', 'dir': 'c1', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/', 'fetched': true, 'code': 200, 'len': 132, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': true, 'child_cnt': 5, 'issue_cnt': [ 15, 4, 0, 6, 0 ], 'sig': 0xb7499cf6 },
  { 'dupe': false, 'type': 4, 'name': 'api', 'dir': 'c2', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/', 'fetched': true, 'code': 200, 'len': 132, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': true, 'child_cnt': 1, 'issue_cnt': [ 5, 1, 0, 2, 0 ], 'sig': 0xb7489cf6 },
  { 'dupe': false, 'type': 4, 'name': 'api', 'dir': 'c3', 'linked': 2, 'url': 'http://127.0.0.1:8000/api/', 'fetched': true, 'code': 406, 'len': 57, 'decl_mime': 'application/json', 'sniff_mime': 'application/javascript', 'cset': '[none]', 'missing': false, 'csens': true, 'child_cnt': 0, 'issue_cnt': [ 2, 0, 0, 3, 0 ], 'sig': 0xa4a695f },
  { 'dupe': false, 'type': 4, 'name': 'camera', 'dir': 'c4', 'linked': 0, 'url': 'http://127.0.0.1:8000/camera/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 1, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': false, 'type': 4, 'name': 'forgot-password', 'dir': 'c5', 'linked': 2, 'url': 'http://127.0.0.1:8000/forgot-password/', 'fetched': true, 'code': 500, 'len': 84770, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 1, 0, 0, 2, 0 ], 'sig': 0xbe167e91 },
  { 'dupe': false, 'type': 4, 'name': 'home', 'dir': 'c6', 'linked': 1, 'url': 'http://127.0.0.1:8000/home/', 'fetched': true, 'code': 404, 'len': 5136, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': '[none]', 'missing': true, 'csens': false, 'child_cnt': 14, 'issue_cnt': [ 0, 0, 0, 14, 0 ], 'sig': 0x11683cc5 },
  { 'dupe': false, 'type': 4, 'name': 'login', 'dir': 'c7', 'linked': 5, 'url': 'http://127.0.0.1:8000/login/', 'fetched': true, 'code': 200, 'len': 3835, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 3, 'issue_cnt': [ 4, 0, 0, 9, 0 ], 'sig': 0x91525812 },
  { 'dupe': false, 'type': 4, 'name': 'maps', 'dir': 'c8', 'linked': 0, 'url': 'http://127.0.0.1:8000/maps/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 3, 0 ], 'sig': 0xd6b178f1 },
  { 'dupe': true, 'type': 4, 'name': 'profile', 'dir': 'c9', 'linked': 0, 'url': 'http://127.0.0.1:8000/profile/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': false, 'type': 4, 'name': 'register', 'dir': 'c10', 'linked': 5, 'url': 'http://127.0.0.1:8000/register/', 'fetched': true, 'code': 200, 'len': 3925, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 4, 'issue_cnt': [ 1, 0, 0, 9, 0 ], 'sig': 0x9c41e533 },
  { 'dupe': true, 'type': 4, 'name': 'road-export-excel', 'dir': 'c11', 'linked': 2, 'url': 'http://127.0.0.1:8000/road-export-excel/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': true, 'type': 4, 'name': 'roadGerald', 'dir': 'c12', 'linked': 0, 'url': 'http://127.0.0.1:8000/roadGerald/', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': false, 'child_cnt': 0, 'issue_cnt': [ 0, 0, 0, 0, 0 ], 'sig': 0x210ddfc3 },
  { 'dupe': false, 'type': 4, 'name': 'static', 'dir': 'c13', 'linked': 2, 'url': 'http://127.0.0.1:8000/static/', 'fetched': true, 'code': 404, 'len': 1868, 'decl_mime': 'text/html', 'sniff_mime': 'application/xhtml+xml', 'cset': 'utf-8', 'missing': true, 'csens': false, 'child_cnt': 21, 'issue_cnt': [ 57, 0, 0, 0, 0 ], 'sig': 0x81e417d6 },
  { 'dupe': false, 'type': 16, 'name': 'admin', 'dir': 'c14', 'linked': 5, 'url': 'http://127.0.0.1:8000/admin', 'fetched': true, 'code': 302, 'len': 0, 'decl_mime': 'text/html', 'sniff_mime': '[none]', 'cset': 'utf-8', 'missing': false, 'csens': true, 'child_cnt': 5, 'issue_cnt': [ 3, 1, 0, 8, 0 ], 'sig': 0xd756829f }
];
